export default  {
    'PARK': 'Park',
    'TOURIST_DESTINATION': 'Tourist Destination',
    'MUSEUM': 'Cultural Heritage',
    'HISTORICAL': 'Cultural Heritage',
    'SCENIC_POINT': 'Scenic Landmarks',
    'BRIDGE': 'Scenic Landmarks',
    'NATURE_RESERVE': 'Nature Attractions',
    'ZOO': 'Nature Attractions',
    'BOTANICAL_GARDEN': 'Nature Attractions',
    'ARTS': 'Art',
    'DESSERT': 'Art',
    'CHURCH': 'Religious',
    'SYNAGOGUE': 'Religious',
    'VISITOR_CENTER': 'Tourist Destination',
    'LIBRARY': 'Library',
    'SHOPPING_CENTER': 'Shopping Center',
    'APPAREL': 'Fashion Convenience',
    'OTHER': 'Tourist Destination',
    'SHOPPING': 'Fashion Convenience',
    'CONVENIENCE_STORE': 'Neighborhood Market',
    'SUPERMARKET': 'Neighborhood Market',
    'GROCERY': 'Neighborhood Market',
    'MARKET': 'Neighborhood Market',
    'GIFTS': 'Gifts & Souvenirs',
    'SOUVENIR_SHOP': 'Gifts & Souvenirs',
    
}